/**
 * @file StructureController.hpp
 * @brief Represents a room controller structure.
 * 
 * This file defines the StructureController class which represents the
 * controller structure in a room. Controllers are used to claim rooms,
 * upgrade room levels, and manage room settings.
 */

#ifndef SCREEPS_STRUCTURE_CONTROLLER_HPP
#define SCREEPS_STRUCTURE_CONTROLLER_HPP

#include "OwnedStructure.hpp"

#include <ctime>
#include <optional>

namespace Screeps {

/**
 * @class StructureController
 * @brief The controller structure that determines room ownership and level.
 * 
 * A StructureController (or simply "controller") is the central structure
 * in a room that determines ownership and room level. Controllers:
 * - Can be claimed to take ownership of a room
 * - Can be upgraded to increase room level (1-8)
 * - Provide access to safe mode for room protection
 * - Control which structures can be built in the room
 * 
 * Room controller levels determine:
 * - Which structures can be built
 * - How many of each structure can be built
 * - The room's energy capacity
 * - And other room capabilities
 * 
 * The room controller can be accessed through Room::controller().
 * 
 * @see OwnedStructure, Creep::claimController(), Creep::upgradeController(), Room::controller()
 */
class StructureController : public OwnedStructure
{
public:
	/**
	 * @struct Reservation
	 * @brief Information about a controller reservation.
	 * 
	 * A reservation temporarily blocks a neutral controller from being
	 * claimed by other players.
	 */
	struct Reservation
	{
		/** @brief The username of the player who reserved the controller. */
		std::string username;
		/** @brief The number of ticks until the reservation ends. */
		int ticksToEnd;
	};

	/**
	 * @struct Sign
	 * @brief Information about a controller sign.
	 * 
	 * A sign is a text message displayed on the controller that is visible
	 * to all players.
	 */
	struct Sign
	{
		/** @brief The username of the player who signed the controller. */
		std::string username;
		/** @brief The sign text. */
		std::string text;
		/** @brief The game tick when the controller was signed. */
		int time;
		/** @brief The real-world timestamp when the controller was signed (ms since epoch UTC). */
		std::int64_t datetime;
	};

	/**
	 * @brief Construct a StructureController from a JavaScript value.
	 * @param value The JavaScript controller value.
	 */
	explicit StructureController(JS::Value value);

	/**
	 * @brief Check if power is enabled in this room.
	 * 
	 * Power must be enabled to use Power Creep abilities in the room.
	 * Use PowerCreep::enableRoom() to enable power.
	 * 
	 * @return bool True if power is enabled, false otherwise.
	 * 
	 * @see PowerCreep::enableRoom()
	 */
	bool isPowerEnabled() const;

	/**
	 * @brief Get the current controller level (1-8).
	 * @return int The controller level.
	 */
	int level() const;

	/**
	 * @brief Get the current progress towards the next level.
	 * @return int The current progress amount.
	 */
	int progress() const;

	/**
	 * @brief Get the total progress needed to reach the next level.
	 * @return int The progress required for the next level.
	 */
	int progressTotal() const;

	/**
	 * @brief Get the controller reservation information.
	 * @return std::optional<Reservation> Reservation info if reserved, or nullopt.
	 * 
	 * @see Reservation
	 */
	std::optional<Reservation> reservation() const;

	/**
	 * @brief Get the remaining safe mode ticks.
	 * @return std::optional<int> Safe mode ticks remaining, or nullopt if not active.
	 */
	std::optional<int> safeMode() const;

	/**
	 * @brief Get the number of safe mode activations available.
	 * 
	 * Each new controller level generates one available activation.
	 * Can also be generated by creeps using 1000 ghodium.
	 * 
	 * @return int The number of safe mode activations available.
	 */
	int safeModeAvailable() const;

	/**
	 * @brief Get the safe mode cooldown period.
	 * @return std::optional<int> Cooldown ticks remaining, or nullopt if inactive.
	 */
	std::optional<int> safeModeCooldown() const;

	/**
	 * @brief Get the controller sign information.
	 * @return std::optional<Sign> Sign info if signed, or nullopt.
	 * 
	 * @see Sign, Creep::signController()
	 */
	std::optional<Sign> sign() const;

	/**
	 * @brief Get the ticks until the controller downgrades.
	 * 
	 * The controller downgrades one level when this timer reaches 0.
	 * Upgrading the controller increases this timer by 100.
	 * The timer must be full to upgrade the controller.
	 * 
	 * @return int The ticks until downgrade.
	 */
	int ticksToDowngrade() const;

	/**
	 * @brief Get the ticks while the controller cannot be upgraded.
	 * 
	 * This is set when the controller is attacked and prevents upgrading
	 * for a period of time.
	 * 
	 * @return int The upgrade blocked ticks remaining.
	 */
	int upgradeBlocked() const;

	/**
	 * @brief Activate safe mode for the room.
	 * 
	 * Blocks hostile creep actions in the room for 20,000 ticks.
	 * Can only be activated if safe mode is available and not on cooldown.
	 * Only one room can be in safe mode at a time.
	 * 
	 * @return int Error code:
	 *   - OK (0): Success
	 *   - ERR_NOT_OWNER (-1): Not your controller
	 *   - ERR_BUSY (-4): Another room is already in safe mode
	 *   - ERR_NOT_ENOUGH_RESOURCES (-6): No safe mode activations available
	 *   - ERR_TIRED (-11): Safe mode is on cooldown, controller is upgradeBlocked,
	 *     or controller is downgraded for 50% + 5000 ticks or more
	 * 
	 * @see safeMode(), safeModeAvailable(), safeModeCooldown()
	 */
	int activateSafeMode();

	/**
	 * @brief Make your claimed controller neutral again.
	 * 
	 * Releases ownership of the controller, making it neutral.
	 * 
	 * @return int Error code:
	 *   - OK (0): Success
	 *   - ERR_NOT_OWNER (-1): Not your controller
	 * 
	 * @see Creep::claimController()
	 */
	int unclaim();
};

} // namespace Screeps

#endif // SCREEPS_STRUCTURE_CONTROLLER_HPP
